/**
 * \file
 *
 * \brief User board configuration template
 *
 * Copyright (c) 2013-2018 Microchip Technology Inc. and its subsidiaries.
 *
 * \asf_license_start
 *
 * \page License
 *
 * Subject to your compliance with these terms, you may use Microchip
 * software and any derivatives exclusively with Microchip products.
 * It is your responsibility to comply with third party license terms applicable
 * to your use of third party software (including open source software) that
 * may accompany Microchip software.
 *
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE,
 * INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY,
 * AND FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT WILL MICROCHIP BE
 * LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL
 * LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND WHATSOEVER RELATED TO THE
 * SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS BEEN ADVISED OF THE
 * POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE FULLEST EXTENT
 * ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN ANY WAY
 * RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
 * THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * \asf_license_stop
 *
 */
/*
 * Support and FAQ: visit <a href="https://www.microchip.com/support/">Microchip Support</a>
 */

#ifndef CONF_BOARD_H
#define CONF_BOARD_H

#define CONF_BOARD_USB_VBUS_DETECT

#define SSD1306_I2C_ADDRESS   0x3C
#define SSD1306_128_64

#define BOARD_FREQ_SLCK_XTAL      (32768U)
#define BOARD_FREQ_SLCK_BYPASS    (32768U)
#define BOARD_FREQ_MAINCK_XTAL    0 /* Not Mounted */
#define BOARD_FREQ_MAINCK_BYPASS  0 /* Not Mounted */
#define BOARD_MCK                 CHIP_FREQ_CPU_MAX
#define BOARD_OSC_STARTUP_US      15625

#define	TP_1				PIN_PA03
#define	TP_2				PIN_PA08
#define	TP_3				PIN_PA09
#define	TP_4				PIN_PA10
#define	TP_5				PIN_PA11

#define ANALOG_0_PIN		TP_1
#define USB_VOLTAGE_PIN		PIN_PB03

#define CHARGE_STATUS		PIN_PA21

#define SW0_PIN				PIN_PA07
#define BUTTON_0_NAME       "CAL"
#define BUTTON_0_PIN        SW0_PIN
#define BUTTON_0_ACTIVE     false
#define BUTTON_0_INACTIVE   true
#define BUTTON_0_EIC_PIN    PIN_PA07A_EIC_EXTINT7
#define BUTTON_0_EIC_MUX    MUX_PA07A_EIC_EXTINT7
#define BUTTON_0_EIC_PINMUX	PINMUX_PA07A_EIC_EXTINT7
#define BUTTON_0_EIC_LINE   7

#define SW1_PIN				PIN_PA02
#define BUTTON_1_NAME       "ZER"
#define BUTTON_1_PIN        SW1_PIN
#define BUTTON_1_ACTIVE     false
#define BUTTON_1_INACTIVE   true
#define BUTTON_1_EIC_PIN    PIN_PA02A_EIC_EXTINT2
#define BUTTON_1_EIC_MUX    MUX_PA02A_EIC_EXTINT2
#define BUTTON_1_EIC_PINMUX	PINMUX_PA02A_EIC_EXTINT2
#define BUTTON_1_EIC_LINE   7

// SPI SENSOR (SERCOM 1/3)
#define SENSOR_SPI_SS_1     PIN_PA20
#define SENSOR_SPI_SS_0     PIN_PA17

#define SENSOR_SPI_SCK		PIN_PA19
#define SENSOR_SPI_MOSI		PIN_PA18
#define SENSOR_SPI_MISO		PIN_PA16

#define SENSOR_SERCOM		SERCOM1

#define CONF_MASTER_MUX_SETTING	SPI_SIGNAL_MUX_SETTING_E
#define CONF_MASTER_PINMUX_PAD0 PINMUX_PA16C_SERCOM1_PAD0
#define CONF_MASTER_PINMUX_PAD1	PINMUX_UNUSED
#define CONF_MASTER_PINMUX_PAD2 PINMUX_PA18C_SERCOM1_PAD2
#define CONF_MASTER_PINMUX_PAD3	PINMUX_PA19C_SERCOM1_PAD3

//I²C DISPLAY (SERCOM 2/4)
#define DOSPLAY_SERCOM		SERCOM2

#define SCL_DISP_PIN		PIN_PA13
#define SDA_DISP_PIN		PIN_PA12

#define DISPLAY_I2C_SERCOM_PINMUX_PAD0  PINMUX_PA12C_SERCOM2_PAD0
#define DISPLAY_I2C_SERCOM_PINMUX_PAD1  PINMUX_PA13C_SERCOM2_PAD1

#endif // CONF_BOARD_H
